# Generated by Django 3.2 on 2022-02-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('views_cnt', models.IntegerField(blank=True, null=True)),
                ('impressions_cnt', models.IntegerField(default=1)),
                ('text_length', models.IntegerField(blank=True, null=True)),
                ('image_cnt', models.IntegerField(blank=True, default=1, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('importance', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
