# Generated by Django 3.2 on 2022-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
