# Generated by Django 3.2 on 2022-02-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0002_alter_testdata_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testdata',
            old_name='test_length',
            new_name='text_length',
        ),
    ]
