# Generated by Django 3.2 on 2022-02-09 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0003_rename_test_length_testdata_text_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='image_cnt',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
