# Generated by Django 3.2 on 2022-02-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0006_alter_testdata_impressions_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='importance',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
