# Generated by Django 3.2 on 2022-02-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testproject', '0007_testdata_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='impressions_cnt',
            field=models.IntegerField(default=1),
        ),
    ]
